### ISSUE TITLE
repository cannot be initialized

### ISSUE THREAD

**Issue by olivernybroe** [syncany/syncany-plugin-webdav#1]
http://i.imgur.com/FZIbrKt.png
Here is a picture of my terminal, this is in Windows with ver. 0.2.0 of Syncany.

**Comment by olivernybroe** [comment]
Okay, so by deleting the old userconfig file I was able to make the system not giving the first error. 
But it still comes with the the other error.

**Comment by olivernybroe** [comment]
Okay I found the problem, first I had an old version of webdav, and secondly I had also not specified a folder on my server other then the root.

**Comment by cr0** [comment]
If you use `--create-target` syncany will create the given folder is possible. Have a look at the [sy init manpage](http://syncany.readthedocs.org/en/latest/appendix_man_pages.html#man-init).

Furthermore, please use our [main issue tracker](https://github.com/syncany/syncany/issues) next time.
Closing this.
